### ISSUE TITLE
Colour input not showing on entry

### ISSUE THREAD

**Issue by alecritson** [supercool/Button-Box#5]
Hey,

I was trying to use the colour button fieldtype and nothing renders on the entry page, the markup is in the source and there are no errors that I can see in the console yet all that shows is the label. I'm using Craft 2.3.2617 if that helps.

![colour-input](https://cloud.githubusercontent.com/assets/1488016/5327517/f6821222-7d49-11e4-819d-b9cc57005f78.jpg)

These are my fieldtype settings:

![colour-settings](https://cloud.githubusercontent.com/assets/1488016/5327519/0509fd5a-7d4a-11e4-86f4-8eca7291fc91.jpg)

Thanks!

**Comment by julzmon** [comment]
Setting a default color no longer works in latest Craft release.

**Comment by joshangell** [comment]
Thanks @julzmon - I'm planning on taking a look at this sometime this week, feel free to patch and send a PR.

**Comment by joshangell** [comment]
Hi @julzmon - I can't reproduce the problem you're seeing, are you sure setting a default doesn't work?
